### ISSUE TITLE
Crash issues with spotify v8.7.70 

### ISSUE THREAD

**Issue by Lmfaoooooooo** [purp0s3/Tweaked-iOS-Apps#10]
okay so everytime i try to open it, it crashes, i don't know if it's what i use to install it or just my ios version that isn't compatible with it. current version im on is ios 14.7.1 if there's a fix please let me know thanks 🙏

**Comment by purp0s3** [comment]
What device? Sideloaded or installed via TrollStore/AppSync? Did you try the older version available to test if it crashes too?
