### ISSUE TITLE
[Request] Upload the old Tiktok26.5.0_DLTiktok1.9.3

### ISSUE THREAD

**Issue by trxshnumb** [purp0s3/Tweaked-iOS-Apps#14]
the new version aint working for me it shows no internet connection also cant acess the addon page its blank, i accidentally deleted the old version tiktok please share a link coz that version worked fine for me 🙏🏻

**Comment by trxshnumb** [comment]
solved, got the old version by using the wayback machine website 😉

**Comment by purp0s3** [comment]
You just had to go through old releases but ok
