### ISSUE TITLE
Spotify 8.8.6 + Spotilife 1.8 crashes Altstore 1.6

### ISSUE THREAD

**Issue by Ed3n18** [purp0s3/Tweaked-iOS-Apps#15]
Tried spotify 8.x multiple times but it either throws an error or crashes Altstore. Spotify 8.7 seems to work fine but i would like to upgrade.

iPhone 13 Pro Max
iOS 16.3

**Comment by purp0s3** [comment]
Use Sideloadly.

**Comment by purp0s3** [comment]
Spotify specifically when using altstore gives an error that I'm not able to fix. If you install it with sideloadly you might be able to refresh it through altstore tho.

**Comment by Ed3n18** [comment]
Okay, will check that. Thanks

**Comment by Be8947** [comment]
I tryied using sideload and it blocked my phone, do u know why?

**Comment by purp0s3** [comment]
blocked how

**Comment by purp0s3** [comment]
I don't know why your phone got blocked, don't use 3utools nor recommend it. Just use sidealoadly. Simple.

**Comment by Be8947** [comment]
I changed ID to use sideloadly, but still didnt finish installing spotify =(
And btw, thanks so much for uploading ipa for us man! Much appreciated!

**Comment by Ed3n18** [comment]
Yeah do not use 3utools, its known to be bad. And thank you for the .ipas that you update regularly :)
