### ISSUE TITLE
Instagram rocket Issue on app v272.0 tweak v3.8.5

### ISSUE THREAD

**Issue by kevin-hub2020** [purp0s3/Tweaked-iOS-Apps#19]
- Rocket can only download photos and videos from stories, not from profiles or home or in Search tab
- Cannot scroll down on reels or videos.
- Rocket does not make its own folder on the Files app, only app version 236.1 with tweak version 3.7.42 does make a folder on the Files app.

**Comment by purp0s3** [comment]
Works fine for me, using it daily. Device? Version? Method used?

**Comment by justin0386** [comment]
Not working for me either. I am on iPhone 14 pro max iOS 16.3.1 and using the sideloaded ipa

**Comment by kevin-hub2020** [comment]
> Works fine for me, using it daily. Device? Version? Method used?

iPhone 14 pro max ios 16.1.1 using signolous, sorry for the late reply.

**Comment by purp0s3** [comment]
try now

**Comment by kevin-hub2020** [comment]
> try now

It works! Stories can be saved and posts too. But now the stories don’t show up on grid view, only on List Layout.
