### ISSUE TITLE
Twitter keeps logging out

### ISSUE THREAD

**Issue by icpryde** [purp0s3/Tweaked-iOS-Apps#2]
I notice I’ll put my credentials into twitter but then after a day or so when I open twitter again it wants me to put them in again.

doesn’t seem to remember I logged in already?

this is using the latest version 

Twitter9.34_BHTwitter3.2.ipa

**Comment by purp0s3** [comment]
I've seen others users complain about this issue. Did you use TrollStore or it's sideloaded? 

Don't really know why it's happening to you and a small portion of people. I've been using my .ipa via TrollStore since I released it and didn't face this once.

**Comment by icpryde** [comment]
sideload using signulous on my iphone 14 pro

**Comment by purp0s3** [comment]
So it also can be related to iOS 16... Maybe try using Sideloadly or the outdated .ipa from the dev's official [release](https://github.com/BandarHL/BHTwitter/releases). If you still face this issue, it's up to @BandarHL.
