### ISSUE TITLE
Duolingo Tweaked Bundle Error

### ISSUE THREAD

**Issue by electroniix** [purp0s3/Tweaked-iOS-Apps#20]
Hey. Installation works fine, but when trying to learn, i get a bundle error. Can you help?

**Comment by purp0s3** [comment]
Learn what exactly?

**Comment by electroniix** [comment]
After any level i join in portuguese, it crashes with following message
![0833D429-4157-421B-BDA9-050EE98B4DD7](https://user-images.githubusercontent.com/54363303/231481277-cb62b055-f350-4d4d-a648-e79ba567d201.png)

**Comment by purp0s3** [comment]
That's weird, but on the tweak side, I'll see if there are any updates.

**Comment by cri-st** [comment]
Here same problem 😖

**Comment by purp0s3** [comment]
Try the latest release, it's on them now.

**Comment by cri-st** [comment]
The last release is v6.196.0? 
Is the versión with the error

**Comment by purp0s3** [comment]
Link in the repository now redirects to the developer's release. 

At first I repacked it with a clean Duolingo ipa but there's this issue I cant solve so, either their ipa works or their ipa works because I cant do nothing about it.
