### ISSUE TITLE
Asking for Xcode

### ISSUE THREAD

**Issue by Be8947** [purp0s3/Tweaked-iOS-Apps#22]
Hey friend, sorry for bothering!
Tried to install the same way as always, but now it keep asking for XCode Token! Do u know why is doing that? Thanks!

**Comment by purp0s3** [comment]
Which method are you using to install?

**Comment by Be8947** [comment]
Tried with Sideload and 3uTools

**Comment by purp0s3** [comment]
I'm not familiar with the tool and never seen this error in my tests, maybe it's related to your software/OS.

**Comment by Be8947** [comment]
okay, I'll try in another pc. Thanks
