### ISSUE TITLE
update DLTiktok

### ISSUE THREAD

**Issue by trxshnumb** [purp0s3/Tweaked-iOS-Apps#23]
there must be a fix for the tweak its been a while now, the developer must've fixed the tweak for new version of tiktok.
please try to look into this 🙏🏻
thanks for your works, appreciate it.

**Comment by purp0s3** [comment]
Just checked and v27+ is still not working properly, unfortunately this is the latest version that works flawlessly. 

I'm still checking from time to time and when an update is available I'll release it. Make sure to star the repository to be informed.
