### ISSUE TITLE
Installed Spotify with Spotilife but didnt work

### ISSUE THREAD

**Issue by nikosszzz** [purp0s3/Tweaked-iOS-Apps#26]
It shows Spotilife in the settings but theres no skips available, loop unavailable. Its like the normal spotify app.

**Comment by purp0s3** [comment]
Did you enable it? What device, version and method used?

**Comment by wjz050726** [comment]
> Did you enable it? What device, version and method used?

iphone13 with ios16.6   enabled,but still dont working
