### ISSUE TITLE
[Request] Duolingo 

### ISSUE THREAD

**Issue by icpryde** [purp0s3/Tweaked-iOS-Apps#3]
I was hoping I could request an app and getting the latest version of duolingo, it’s been a long time since it’s been updated.

the latest version I can find is Duolingo_6.170.0_mkarasevych.ipa 

which can be found here:

https://appdb.to/app/cydia/1900000920

you will notice it says v 6.171.0 which isn’t correct it’s the version I listed above
When you download the ipa.

anyway would be great if we could get the updated duolingo v6.188.0 is the latest and get super duolingo.

**Comment by purp0s3** [comment]
there u go
