### ISSUE TITLE
Why including pay-to-use tweaks?

### ISSUE THREAD

**Issue by MisterSirCode** [purp0s3/Tweaked-iOS-Apps#32]
Several of the tweaks (such as the ones for facebook and instagram) are basically paywalled and/or require you to buy a "license" to use their features (Which is kindof bullshit if you ask me... The whole point of the tweak is to remove the nonsense, not add more)

So I don't understand why these are being used.

**Comment by purp0s3** [comment]
1. I'm not the developer of any of them.

2. If it's this bad, I don't understand how hard it is to not use it and go on live your life.

It's an abandoned project anyways so :)

**Comment by MisterSirCode** [comment]
You do you

**Comment by purp0s3** [comment]
Says the "if you ask me" guy after literally no one asked him!
