### ISSUE TITLE
RedditFilter overheats my phone

### ISSUE THREAD

**Issue by le0-VV** [purp0s3/Tweaked-iOS-Apps#33]
Installing and using the RedditFilter app will cause the phone to heat up while wirelessly charging, but not charging using a cable. I've tried charging my phone with and without the app installed and turned off Background App Refresh for the app, and by isolation, I am 100% certain it's the RedditFilter app's issue.

**Comment by catalpaaa** [comment]
doesnt charging wirelessly just heat up ur phoen?

**Comment by le0-VV** [comment]
> doesnt charging wirelessly just heat up ur phoen?

Without the app the phone only heats up to around 37-38c, and the charging stays normal, but with the app the phone heats up beyond 42c, which is too hot for charging to continue. This data is obtained from coconutBattery. This happens even when the app is not active, cleared from the background, and the phone screen turned off. Since I've got the app installed whenever I leave my phone on the charging stand over night it just won't charge and I'm left with a flat battery in the morning.

**Comment by le0-VV** [comment]
> doesnt charging wirelessly just heat up ur phoen?

<img width="371" alt="Screenshot 2023-07-13 at 9 08 35 pm" src="https://github.com/purp0s3/Tweaked-iOS-Apps/assets/40534994/b8156f94-42a9-467d-aaf2-8a082f265b5b">

This is not normal

**Comment by purp0s3** [comment]
Hey, I haven't noticed this bug nor had anyone reporting this to me. Anyways, I'm not the developer of the tweak so your best bet is to talk to them.
