### ISSUE TITLE
Always Start On Follow Page Bug

### ISSUE THREAD

**Issue by thesoloist-1** [purp0s3/Tweaked-iOS-Apps#37]
When "always start on follow page" is active, scrolling gets stuck and forces you back to the top of the following page. Also if you are on any other list page and you try to scroll, it throws you back to the following page.

https://github.com/purp0s3/Tweaked-iOS-Apps/assets/97246028/a0fec2f9-9355-4be6-b86a-6905f27e0f35

**Comment by purp0s3** [comment]
Yea, I noticed this bug too but unfortunately I'm not the developer of the tweak so we just gotta hope he fixes it.
