### ISSUE TITLE
Rocket Instagram

### ISSUE THREAD

**Issue by Be8947** [purp0s3/Tweaked-iOS-Apps#38]
Hey mate, sorry for bothering you again, is there a new version of Rocket Instagram? I can install the IPA from your page anymore.
If there is a new one can you update, please?
If there is a new version for Twitter BHT too, please update it as well, please!
Thank you so much!

**Comment by halkun** [comment]
Unfortunately you'll want to refer to this https://github.com/purp0s3/Tweaked-iOS-Apps/issues/39

**Comment by purp0s3** [comment]
Check it out!
