### ISSUE TITLE
Spotilife not working

### ISSUE THREAD

**Issue by D3ADHUNT3RS** [purp0s3/Tweaked-iOS-Apps#40]
I'm on ios 16.6.1 iPhone 12PM using altstore didn't work so I used Sideloadly but the tweak doesn't work. I basically have the free Spotify app.

**Comment by purp0s3** [comment]
Try now.

**Comment by hf-ikea** [comment]
I can confirm, I have tried your release and others, does not work on my IOS 16.0 iPhone 11, using sideloadly on windows.
It might be a problem with Spotilife 1.8 and the new versions of spotify
