### ISSUE TITLE
Plus for Instagram is broken

### ISSUE THREAD

**Issue by RobyRew** [purp0s3/Tweaked-iOS-Apps#6]
Hi, first of all thanks for all you are doing.

I want to inform you that your provided "Plus IPA" crash the app when trying to access any profile or Plus's Settings. 
But I know why, latest **Plus for Instagram** compatibility is` IG_v245.0 `with` Plus_for_IG_v2.50` so the version is on your repo is too new that is not working.

My question is how you made that IPA to not crash on open. Could you capture the screen, make some screenshots, commands or explain how you made that Plus for Instagram tweak? I just tried everything I could.

I've been looking for making a IPA for Plus for Instagram although neither Azule's result give me success, crash on launch, or Sideloadly's (trying all possible configurations).

Here's how I make other IPA's Plus for instagram doesn't work for some reason.
![201186736-25c56e50-36ae-4230-85a7-fab245f536e0](https://user-images.githubusercontent.com/49403384/201343651-fcc3b222-2d1b-4ae3-9ee5-ecd2695fbc22.png)

Thanks again!

Edit: Im using TrollStore too, so I don't have that many restrictions.

**Comment by purp0s3** [comment]
Sorry for the late response. To be honest I don't remeber how I compiled it but I think it was using theos-jailed. Either way, make sure your entitlements are correct, inject all dependencies and use -S on azule so you compiled a fakesigned .ipa to use with TrollStore.

**Comment by RobyRew** [comment]
> Sorry for the late response. To be honest I don't remeber how I compiled it but I think it was using theos-jailed. Either way, make sure your entitlements are correct, inject all dependencies and use -S on azule so you compiled a fakesigned .ipa to use with TrollStore.

Thanks for the theos-jailed, I informed you also in the issue that the version you are sharing is not working and its crashing, I hope you cant take a look (latest officially supported is on the thread up here)
