### ISSUE TITLE
unlimited likes on tinder doesn't work

### ISSUE THREAD

**Issue by essie98927** [purp0s3/Tweaked-iOS-Apps#7]
I'm on IOS 16.1 using an iPhone 11 pro and signulous

No blurred photos is working but not the unlimited like feature on Tinder... After a certain quantity of likes it tells me to wait 12 hours as usual...

**Comment by janiktest** [comment]
obviously,

api request are not cheatable lmao

**Comment by purp0s3** [comment]
It used to work (by the time I released this, I got a tester who made sure it bypassed the limit), but Tinder patched this server-sided so unless someone else bypasses it again no unlimited likes. _it may have already happened, I just don't use the app and I'm not up to date with it's tweaks_
