### ISSUE TITLE
Edit playlist feature in spotify 8.7.70 spotilife 1.8 is wack

### ISSUE THREAD

**Issue by jxjot** [purp0s3/Tweaked-iOS-Apps#9]
I cant edit and rearrange the songs in the spotify playlist. I cant drag the song to top or bottom, i can only remove the song. Is there a fix? Im on ios 15.6.1 and ios 15.1, it has issue on both devices.

**Comment by purp0s3** [comment]
Spotilife latest fully supported version is 8.5.60, using it on newer versions may cause bugs like this. Use the older one, it's in the repo aswell.
